name: TinyTapeout CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  synthesis:
    runs-on: ubuntu-24.04
    name: RTL Synthesis with Yosys and OpenLane
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Yosys and OpenLane
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang bison flex
          git clone https://github.com/YosysHQ/yosys.git
          git clone https://github.com/efabless/openlane.git

      - name: Run Yosys synthesis
        run: |
          cd yosys
          make

      - name: Run OpenLane for placement & routing
        run: |
          cd openlane
          ./flow.tcl -design path_to_your_design

  gdsii_generation:
    needs: synthesis
    runs-on: ubuntu-24.04
    name: GDSII Generation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run OpenLane for GDSII generation
        run: |
          cd openlane
          ./flow.tcl -design path_to_your_design -run gdsii

  precheck:
    needs: gdsii_generation
    runs-on: ubuntu-24.04
    name: Precheck the GDSII Output
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25b
        with:
          pdk: sky130

  upload_artifacts:
    needs: gdsii_generation
    runs-on: ubuntu-24.04
    name: Upload GDSII Files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Upload GDSII Files
        uses: actions/upload-artifact@v4
        with:
          name: gdsii-files
          path: /path/to/your/generated/gdsii/file.gds
